name: 'TSLint checks'
description: 'GitHub action that lints your code with TSLint (with Annotation support)'
author: 'MooYeol Prescott Lee'
inputs:
  token:
    description: 'Github Token'
    required: true
  project:
    description: 'Path of TypeScript Project file'
  config:
    description: 'Path of TSLint configuration'
    default: 'tslint.json'
  pattern:
    description: 'Glob pattern to match'
  only-changed:
    description: 'Apply glob patter only to changed files'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'code'
  color: 'blue'
